import os

html_template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <link rel="stylesheet" href="style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap" rel="stylesheet">
</head>
<body>
    <div class="background-canvas" id="canvas-container"></div>
    <header class="glass-nav">
        <div class="logo">{short_title}</div>
        <nav>
            <a href="#about">About</a>
            <a href="#features">Features</a>
            <a href="#contact">Contact</a>
        </nav>
    </header>

    <main>
        <section class="hero glass-panel">
            <h1 id="hero-headline">Loading...</h1>
            <p id="hero-intro">Content being generated by NotebookLM AI...</p>
            <button class="cta-button">Discover the Solution</button>
        </section>

        <section id="features" class="features-grid">
            <div class="feature-card glass-panel">
                <h3>Feature 1</h3>
                <p id="feature-1">Loading AI content...</p>
            </div>
            <div class="feature-card glass-panel">
                <h3>Feature 2</h3>
                <p id="feature-2">Loading AI content...</p>
            </div>
            <div class="feature-card glass-panel">
                <h3>Feature 3</h3>
                <p id="feature-3">Loading AI content...</p>
            </div>
        </section>
    </main>

    <footer class="glass-footer">
        <p>&copy; 2026 {short_title}. Powered by Advanced Permeable Technology.</p>
    </footer>
    
    <!-- Script to dynamically load the generated content.md -->
    <script>
        fetch('content.md')
            .then(r => r.text())
            .then(text => {{
                console.log("Loaded content.md");
                // Very basic parser for the placeholder
                document.getElementById('hero-intro').innerText = "Content loaded! Edit HTML to format properly.\\n" + text.substring(0, 150) + "...";
            }})
            .catch(e => console.error("Content not ready yet", e));
    </script>
</body>
</html>
"""

css_template = """* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Inter', sans-serif;
}

body {
    background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
    color: #ffffff;
    min-height: 100vh;
    overflow-x: hidden;
}

.background-canvas {
    position: fixed;
    top: 0; left: 0; right: 0; bottom: 0;
    z-index: -1;
    background: radial-gradient(circle at 50% 50%, rgba(76, 161, 175, 0.2), transparent 60%);
}

.glass-nav, .glass-panel, .glass-footer {
    background: rgba(255, 255, 255, 0.05);
    backdrop-filter: blur(16px);
    -webkit-backdrop-filter: blur(16px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
}

.glass-nav {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.5rem 5%;
    position: sticky;
    top: 0;
    z-index: 100;
}

.glass-nav .logo {
    font-weight: 800;
    font-size: 1.5rem;
    letter-spacing: 1px;
    background: linear-gradient(90deg, #4ca1af, #c4e0e5);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

.glass-nav nav a {
    color: #fff;
    text-decoration: none;
    margin-left: 2rem;
    font-size: 0.9rem;
    font-weight: 600;
    text-transform: uppercase;
    transition: color 0.3s ease;
}

.glass-nav nav a:hover { color: #4ca1af; }

main {
    padding: 5rem 5%;
    max-width: 1200px;
    margin: 0 auto;
}

.hero {
    padding: 4rem;
    border-radius: 20px;
    text-align: center;
    margin-bottom: 4rem;
    transform: translateY(0);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}
.hero:hover {
    transform: translateY(-5px);
    box-shadow: 0 15px 40px rgba(76, 161, 175, 0.2);
}

.hero h1 {
    font-size: 3.5rem;
    margin-bottom: 1.5rem;
    line-height: 1.2;
}

.hero p {
    font-size: 1.2rem;
    color: #e0e0e0;
    margin-bottom: 2.5rem;
    max-width: 800px;
    margin-left: auto;
    margin-right: auto;
}

.cta-button {
    padding: 1rem 2.5rem;
    font-size: 1.1rem;
    font-weight: 600;
    background: linear-gradient(90deg, #4ca1af, #2c5364);
    color: white;
    border: none;
    border-radius: 30px;
    cursor: pointer;
    transition: all 0.3s ease;
    box-shadow: 0 4px 15px rgba(76, 161, 175, 0.4);
}

.cta-button:hover {
    transform: scale(1.05);
    box-shadow: 0 6px 20px rgba(76, 161, 175, 0.6);
}

.features-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 2rem;
}

.feature-card {
    padding: 2.5rem;
    border-radius: 15px;
    transition: all 0.3s ease;
}

.feature-card:hover {
    transform: translateY(-10px);
    background: rgba(255, 255, 255, 0.08);
}

.feature-card h3 {
    font-size: 1.5rem;
    margin-bottom: 1rem;
    color: #c4e0e5;
}

.feature-card p {
    color: #cccccc;
    line-height: 1.6;
}

.glass-footer {
    text-align: center;
    padding: 2rem;
    margin-top: 4rem;
}
"""

projects = [
    ("01_Eco_City_Base", "Eco-City Base", "Eco-City"),
    ("02_Climate_Resilient_Infra", "Climate-Resilient Infratructure", "Climate-Resilient"),
    ("03_Premium_Green_Landscaping", "Premium Green Landscaping", "Premium Green"),
    ("04_ESG_Corporate_Parking", "ESG Corporate Parking", "ESG Parking"),
    ("05_Safe_Dry_School_Zones", "Safe & Dry School Zones", "Safe Zones"),
    ("06_Industrial_Heavy_Duty", "Industrial Heavy-Duty Permeable", "Industrial Duty"),
    ("07_Rainwater_Harvesting_Driveways", "Rainwater Harvesting Driveways", "Rainwater Drive"),
    ("08_Winter_Safe_Paths", "Winter-Safe Paths", "Winter-Safe"),
    ("09_Eco_Trails", "Park & Recreation Eco-Trails", "Eco-Trails"),
    ("10_Sustainable_Urban_Renewal", "Sustainable Urban Renewal", "Urban Renewal")
]

for folder, title, short_title in projects:
    if not os.path.exists(folder):
        os.makedirs(folder)
    
    html_content = html_template.format(title=title, short_title=short_title)
    with open(os.path.join(folder, "index.html"), "w", encoding="utf-8") as f:
        f.write(html_content)
        
    with open(os.path.join(folder, "style.css"), "w", encoding="utf-8") as f:
        f.write(css_template)

print("Scaffolding complete.")
