import os
import re

projects = [
    ("01_Eco_City_Base", "Eco-City Base", "Eco-City"),
    ("02_Climate_Resilient_Infra", "Climate-Resilient Infratructure", "Climate-Resilient"),
    ("03_Premium_Green_Landscaping", "Premium Green Landscaping", "Premium Green"),
    ("04_ESG_Corporate_Parking", "ESG Corporate Parking", "ESG Parking"),
    ("05_Safe_Dry_School_Zones", "Safe & Dry School Zones", "Safe Zones"),
    ("06_Industrial_Heavy_Duty", "Industrial Heavy-Duty Permeable", "Industrial Duty"),
    ("07_Rainwater_Harvesting_Driveways", "Rainwater Harvesting Driveways", "Rainwater Drive"),
    ("08_Winter_Safe_Paths", "Winter-Safe Paths", "Winter-Safe"),
    ("09_Eco_Trails", "Park & Recreation Eco-Trails", "Eco-Trails"),
    ("10_Sustainable_Urban_Renewal", "Sustainable Urban Renewal", "Urban Renewal")
]

for folder, title, short_title in projects:
    content_file = os.path.join(folder, "content.md")
    html_file = os.path.join(folder, "index.html")
    
    if not os.path.exists(content_file) or not os.path.exists(html_file):
        continue
        
    with open(content_file, "r", encoding="utf-8") as f:
        md = f.read()

    # Very naive parser to inject into HTML
    # We look for Headline, Intro, Features etc.
    headline = "Advanced Permeable Solutions"
    intro = "Eco-friendly paving blocks for a sustainable future."
    features = ["Feature 1", "Feature 2", "Feature 3"]
    feature_descs = ["Loading...", "Loading...", "Loading..."]
    
    # Try to extract english parts (heuristic)
    parts = md.split("**")
    for i, p in enumerate(parts):
        if "Headline:" in p or "Headline" in p:
            if i+1 < len(parts): headline = parts[i+1].split("\\n")[0].strip()
        if "Introduction:" in p or "Introduction" in p:
            if i+1 < len(parts): intro = parts[i+1].strip()
            
    # Look for bullet points for features
    bullets = [line.strip() for line in md.split("\\n") if line.strip().startswith("- ") or line.strip().startswith("* ")]
    if len(bullets) >= 3:
        features = [b.split(":")[0][:30].strip("-* ") for b in bullets[:3]]
        feature_descs = [b for b in bullets[:3]]

    with open(html_file, "r", encoding="utf-8") as f:
        html = f.read()
        
    html = html.replace('<h1 id="hero-headline">Loading...</h1>', f'<h1 id="hero-headline">{headline}</h1>')
    html = html.replace('<p id="hero-intro">Content being generated by NotebookLM AI...</p>', f'<p id="hero-intro">{md[:500]}...</p>')
    
    html = html.replace('<h3>Feature 1</h3>', f'<h3>{features[0]}</h3>')
    html = html.replace('<p id="feature-1">Loading AI content...</p>', f'<p id="feature-1">{feature_descs[0]}</p>')
    
    html = html.replace('<h3>Feature 2</h3>', f'<h3>{features[1]}</h3>')
    html = html.replace('<p id="feature-2">Loading AI content...</p>', f'<p id="feature-2">{feature_descs[1]}</p>')
    
    html = html.replace('<h3>Feature 3</h3>', f'<h3>{features[2]}</h3>')
    html = html.replace('<p id="feature-3">Loading AI content...</p>', f'<p id="feature-3">{feature_descs[2]}</p>')
    
    # We will remove the script block so it doesn't try to fetch content.md
    html = re.sub(r'<script>.*?</script>', '', html, flags=re.DOTALL)
    
    with open(html_file, "w", encoding="utf-8") as f:
        f.write(html)
